binop_separator = "Front"
comment_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
reorder_imports = true
wrap_comments = true
